# change to list chars of your dataset or use default vietnamese chars
vocab: '0123456789'
# OR
vocab_file: null
# vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '

# cpu, cuda, cuda:0
device: cuda:0

# Saving options
save_weight: ./weights/transformerocr.pth
save_checkpoint: ./checkpoint/transformerocr_checkpoint.pth
save_log: ./train.log

# Training
training_validate_every: 50
training_num_iters: 100000
training_lr: 0.0003

# Data
data_train_annotation: data/lmnist-ez/train.txt
data_val_annotation: data/lmnist-ez/test.txt
data_batch_size: 50
data_augment: true

# Misc
dataloader_numworker: 8

# Data processing
max_sequence_length: 10
image_width: 128
image_height: 32

# Model
model_backbone: svtr_t
model_head_size: 256
