# change to list chars of your dataset or use default vietnamese chars
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
type: ctc

# weights: https://github.com/ndgnuh/vietocr/releases/download/weights/fvtr_t_ctc.pth
# weights: storage/weights/

stn: vstn

backbone: fvtr_t
cnn:
  output_size: 256
  max_position_ids: 128

seq_modeling: none
transformer:
  head_size: 256

image_height: 32
image_min_width: 32
image_max_width: 512
image_letterbox: false

