# change to list chars of your dataset or use default vietnamese chars
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
type: ctc

# weights: https://github.com/ndgnuh/vietocr/releases/download/weights/sfn_v2_x1_5_s2s.pth
# weights: storage/weights/sfn_v2_x1_5_s2s.pth

backbone: shufflenet_v2_x1_5
cnn:
  dropout: 0.1
  output_size: 256

seq_modeling: none
transformer:
  head_size: 256
  num_attention_heads: 8
  num_layers: 1

image_height: 32
image_min_width: 64
image_max_width: 512


