# New config
learning_rate: 0.0001
total_steps: 1000
validate_every: 100
batch_size: 8

# Loss function
loss: CTCLoss
loss: CrossEntropyLoss

# Dataset
train_annotation: data/black_trdg/train.txt
valid_annotation: data/black_trdg/val.txt
# train_annotation: data/handwriting-address/train.txt
# valid_annotation: data/handwriting-address/val.txt
# train_annotation: data/multi_digit_number_32/train.txt
# valid_annotation: data/multi_digit_number_32/val.txt
train_annotation: data/random-textbox-vi-1k/train.txt
validate_annotation: data/random-textbox-vi-1k/val.txt

# Data loader
dl_batch_size: 8
dl_num_workers: 6
dl_pin_memory: False

# Augmentation
augment: true

# Teacher forcing control
teacher_forcing_start: 0
teacher_forcing_end: 100_000
teacher_forcing_max_prob: 1
